# Generated by Django 5.2.7 on 2025-11-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان پکیج')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('original_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت اصلی (تومان)')),
                ('discounted_price', models.PositiveIntegerField(verbose_name='قیمت تخفیف\u200cخورده (تومان)')),
                ('discount_badge', models.CharField(blank=True, max_length=50, verbose_name='برچسب تخفیف (مثل: ۲۵٪ تخفیف)')),
                ('image', models.ImageField(upload_to='packages/', verbose_name='عکس پکیج')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('is_limited_time', models.BooleanField(default=False, verbose_name='تخفیف موقت باشد؟')),
                ('duration_days', models.PositiveSmallIntegerField(default=3, verbose_name='مدت زمان تخفیف (به روز)')),
            ],
            options={
                'verbose_name': 'پکیج',
                'verbose_name_plural': 'پکیج\u200cها',
            },
        ),
        migrations.CreateModel(
            name='SalonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('open_time', models.TimeField(default='09:00')),
                ('close_time', models.TimeField(default='18:00')),
                ('booking_interval', models.IntegerField(default=15)),
            ],
        ),
    ]
