# Generated by Django 5.2.7 on 2026-02-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salonsettings',
            options={'verbose_name': 'تنظیمات سالن', 'verbose_name_plural': 'تنظیمات سالن'},
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='has_salon_lunch_break',
            field=models.BooleanField(default=False, verbose_name='تعطیل ناهار کل سالن'),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='salon_lunch_end',
            field=models.TimeField(default='14:00', verbose_name='پایان ناهار سالن'),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='salon_lunch_start',
            field=models.TimeField(default='13:00', verbose_name='شروع ناهار سالن'),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='weekend_days',
            field=models.JSONField(default=list, verbose_name='روزهای تعطیل هفتگی'),
        ),
    ]
