# Generated by Django 5.2.7 on 2026-02-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_salonsettings_options_and_more'),
        ('services_app', '0005_alter_popularservice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, related_name='packages', to='services_app.service', verbose_name='خدمت مرتبط'),
        ),
    ]
