# Generated by Django 5.2.7 on 2026-02-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_package_service'),
        ('services_app', '0005_alter_popularservice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='show_on_homepage',
            field=models.BooleanField(default=True, verbose_name='نمایش در صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='package',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='packages', to='services_app.service', verbose_name='خدمت مرتبط'),
        ),
    ]
