# Generated by Django 5.2.7 on 2026-02-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_package_show_on_homepage_alter_package_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='show_on_homepage',
            field=models.BooleanField(default=True, verbose_name='نمایش در سایت'),
        ),
    ]
