# Generated by Django 5.2.7 on 2026-02-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_package_show_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع تخفیف'),
        ),
    ]
