# Generated by Django 5.2.7 on 2026-02-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_package_created_at_package_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(default='packages/package.jpg', upload_to='packages/', verbose_name='عکس پکیج'),
        ),
    ]
