# Generated by Django 5.2.7 on 2026-02-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonsettings',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='مثال: 989123456789 (بدون + و با کد کشور)', max_length=20, null=True, verbose_name='شماره واتس\u200cاپ'),
        ),
    ]
