# Generated by Django 5.2.7 on 2026-02-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_salonsettings_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(upload_to='packages/', verbose_name='عکس پکیج'),
        ),
    ]
