# Generated by Django 5.2.7 on 2026-02-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonsettings',
            name='enable_online_payment',
            field=models.BooleanField(default=False, verbose_name='فعال بودن پرداخت آنلاین'),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='global_duration_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیح سراسری مدت زمان'),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='global_price_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیح سراسری قیمت'),
        ),
    ]
