# Generated by Django 5.2.7 on 2026-02-23 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_salonsettings_enable_online_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonsettings',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره معتبر وارد کنید (موبایل یا تلفن ثابت)', regex='^(09\\d{9}|0\\d{10})$')]),
        ),
    ]
