# Generated by Django 5.2.7 on 2026-02-23 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_salonsettings_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonsettings',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='مثال: 989123456789 (بدون + و با کد کشور)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='شماره واتساپ باید به صورت 989xxxxxxxxx باشد', regex='^989\\d{9}$')], verbose_name='شماره واتس\u200cاپ'),
        ),
    ]
