"""
Django settings for beauty_salon project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import environ
from pathlib import Path

# پیدا کردن مسیر اصلی پروژه (Root)
BASE_DIR = Path(__file__).resolve().parent.parent

# راه‌اندازی environ برای خواندن اطلاعات حساس از فایل .env
env = environ.Env(SECRET_KEY = str,)
environ.Env.read_env(os.path.join(BASE_DIR , '.env'))

# کلید امنیتی پروژه (باید در سرور مخفی بماند)
SECRET_KEY = env('DJANGO_SECRET_KEY')

# حالت دیباگ (برای لوکال True و برای سرور باید False باشد)
DEBUG = env.bool('DJANGO_DEBUG', default=False)

# دامنه‌هایی که سایت اجازه دارد روی آن‌ها اجرا شود
ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# دامنه‌های امن برای جلوگیری از خطای CSRF در فرم‌ها (مخصوصا سمت سرور)
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
if not CSRF_TRUSTED_ORIGINS and ALLOWED_HOSTS:
    CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS if host != '*']

# لیست اپلیکیشن‌ها (اپ‌های پیش‌فرض، پکیج‌های نصب شده و اپ‌های اختصاصی پروژه)
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps
    'core',
    'blog_app',
    'reviews_app.apps.ReviewsAppConfig',
    'services_app',
    'accounts.apps.AccountsConfig',
    'panel',
    'booking.apps.AppointmentReservationConfig',

    # Packages
    'crispy_forms',
    'crispy_bootstrap4',
    'django.contrib.humanize',
    'jalali_date',
    'django_jalali',
    'cloudinary',
    'cloudinary_storage',
]

# لایه‌های واسط برای پردازش ریکوئست‌ها (امنیت، سشن‌ها و...)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',   # برای مدیریت فایل‌های استاتیک در سرور
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'booking.middleware.BookingFlowMiddleware',     # میدل‌ویر اختصاصی سیستم رزرو
]

ROOT_URLCONF = 'beauty_salon.urls'

# تنظیمات مربوط به فایل‌های HTML و دیتای ارسالی به آن‌ها
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,  'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.unread_notifications',
                'panel.context_processors.appointment_counts',  
            ],
        },
    },
]

WSGI_APPLICATION = 'beauty_salon.wsgi.application'


# تنظیمات دیتابیس
# با کمک dj_database_url: در لوکال از sqlite و در سرور به صورت خودکار از postgresql استفاده می‌کند
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'
    )
}


# قوانین اعتبارسنجی و سخت‌گیری برای رمز عبور کاربران
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('username', 'email', 'first_name', 'last_name'),
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# تنظیمات زبان و منطقه زمانی (فارسی و ایران)
LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# مسیر فایل‌های استاتیک (css, js, عکس‌های قالب)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS=[os.path.join(BASE_DIR,  'static')]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# تنظیمات ظاهر فرم‌ها
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"

# هدایت کاربران بعد از ورود و خروج
LOGIN_REDIRECT_URL =  'accounts:profile'   # مسیر پیش‌فرض برای تمام کاربران

LOGOUT_REDIRECT_URL = 'accounts:login'
LOGOUT_REDIRECT_ALLOWED_METHODS = ['GET', 'POST']

LOGIN_URL= 'accounts:login'

# تنظیمات پایه فایل‌های مدیا (عکس‌ها و فایل‌های آپلودی کاربر)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# تنظیمات ارسال ایمیل (از طریق سرور جیمیل)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_TIMEOUT = 5

EMAIL_HOST = "smtp.gmail.com"
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True

EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False

EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD" , default="")
DEFAULT_FROM_EMAIL = 'Beauty Salon <mahlamashrooti@gmail.com>'

# هدرهای امنیتی برای حالت HTTPS در سرور
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False  # فقط در تولید

# امنیت کوکی‌ها (فقط در حالت سرور و غیر دیباگ فعال می‌شود)
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# تشخیص اینکه روی سیستم خودمان هستیم یا سرور
DEBUG_MODE = os.environ.get("DJANGO_DEBUG", "False").lower() in ("true", "1")

if DEBUG_MODE:
    # حالت توسعه (لوکال)
    # فایل‌ها به سادگی روی هارد ذخیره می‌شوند
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }

     # در لوکال نیازی به امنیت کوکی‌های HTTPS نیست
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False

    if "127.0.0.1" not in ALLOWED_HOSTS:
        ALLOWED_HOSTS += ["127.0.0.1", "localhost"]

else:
    # حالت سرور 
    # مدیاها روی فضای ابری (Cloudinary) آپلود می‌شوند تا با ری‌استارت سرور پاک نشوند
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# لاگ‌گیری (نمایش ارورهای دیتابیس در ترمینال برای خطایابی راحت‌تر)
LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'ERROR',
            #DEBUG
        },
    },
}
