# Generated by Django 5.2.7 on 2025-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('receptionist', 'Receptionist'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
