# Generated by Django 5.2.7 on 2025-12-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('leave', 'مرخصی')], default='active', max_length=10),
        ),
    ]
