# Generated by Django 5.2.7 on 2025-12-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار ارسال'), ('sent', 'ارسال شده'), ('read', 'خوانده شده'), ('failed', 'ناموفق')], default='pending', max_length=20),
        ),
    ]
