# Generated by Django 5.2.7 on 2025-12-25 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_bio_profile_city_profile_reminder_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
