# Generated by Django 5.2.7 on 2026-01-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday_change_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
