# Generated by Django 5.2.7 on 2026-01-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
