# Generated by Django 5.2.7 on 2026-01-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_discountcode_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'درصد'), ('fixed', 'مبلغ ثابت')], default='percent', max_length=20),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='min_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
