# Generated by Django 5.2.7 on 2026-01-16 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_discountcode_discount_type_discountcode_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.discountcode'),
        ),
    ]
