# Generated by Django 5.2.7 on 2026-01-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_notification_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='extra_message',
            field=models.TextField(blank=True, default='', verbose_name='متن اضافه برای ایمیل'),
        ),
    ]
