# Generated by Django 5.2.7 on 2026-04-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
