# Generated by Django 5.2.7 on 2025-12-01 13:57

from django.db import migrations, models
import uuid


def generate_tracking_codes(apps, schema_editor):
    Appointment = apps.get_model('booking', 'Appointment')

    for item in Appointment.objects.all():
        # ساخت کد یونیک ۸ کاراکتری برای رکوردهای قدیمی
        item.tracking_code = str(uuid.uuid4())[:8]
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        # مرحله 1: اضافه کردن فیلد با null=True تا خطا ندهد
        migrations.AddField(
            model_name='appointment',
            name='tracking_code',
            field=models.CharField(max_length=20, unique=True, null=True),
        ),

        # مرحله 2: مقداردهی به رکوردهای موجود
        migrations.RunPython(generate_tracking_codes),

        # مرحله 3: حذف null=True و نهایی کردن فیلد
        migrations.AlterField(
            model_name='appointment',
            name='tracking_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
