# Generated by Django 5.2.7 on 2025-12-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='jalali_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
