# Generated by Django 5.2.7 on 2025-12-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointment_jalali_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('leave', 'مرخصی')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('completed', 'انجام شده')], default='pending', max_length=20),
        ),
    ]
