# Generated by Django 5.2.7 on 2025-12-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_pendingappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingappointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
