# Generated by Django 5.2.7 on 2026-01-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_pendingappointment_reminder_sent'),
        ('services_app', '0002_popularservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='staffs', to='services_app.service'),
        ),
    ]
