# Generated by Django 5.2.7 on 2026-02-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_appointment_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس'),
        ),
    ]
