# Generated by Django 5.2.7 on 2026-02-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_appointment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.TextField(blank=True, help_text='توضیحات نمایشی در صفحه درباره ما (مثلاً: «با ۸ سال سابقه و گواهی بین\u200cالمللی»)', null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
