# Generated by Django 5.2.7 on 2026-02-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_staff_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='show_in_about_page',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه درباره ما'),
        ),
    ]
