# Generated by Django 5.2.7 on 2026-02-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_staff_show_in_about_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ میلادی')),
                ('jalali_date', models.CharField(blank=True, max_length=10, verbose_name='تاریخ شمسی')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تعطیلی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('holiday_type', models.CharField(choices=[('official', 'رسمی'), ('religious', 'مذهبی'), ('custom', 'سفارشی')], default='official', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_half_day', models.BooleanField(default=False, verbose_name='نیم\u200cروز')),
                ('half_day_period', models.CharField(blank=True, choices=[('morning', 'صبح'), ('afternoon', 'عصر')], max_length=10, null=True, verbose_name='بازه نیم\u200cروز')),
            ],
            options={
                'verbose_name': 'تعطیلی',
                'verbose_name_plural': 'تعطیلات',
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'پرسنل', 'verbose_name_plural': 'پرسنل\u200cها'},
        ),
        migrations.AddField(
            model_name='staff',
            name='has_lunch_break',
            field=models.BooleanField(default=True, verbose_name='تعطیل ناهار'),
        ),
        migrations.AddField(
            model_name='staff',
            name='lunch_end',
            field=models.TimeField(default='14:00', verbose_name='پایان ناهار'),
        ),
        migrations.AddField(
            model_name='staff',
            name='lunch_start',
            field=models.TimeField(default='13:00', verbose_name='شروع ناهار'),
        ),
    ]
