# Generated by Django 5.2.7 on 2026-02-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_holiday_alter_staff_options_staff_has_lunch_break_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={},
        ),
        migrations.AddField(
            model_name='holiday',
            name='hijri_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='روز قمری'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='hijri_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='ماه قمری'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال میلادی مربوطه'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ میلادی'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('solar', 'شمسی (ثابت)'), ('lunar', 'قمری (متغیر)'), ('custom', 'سفارشی')], default='custom', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('date',), ('hijri_month', 'hijri_day', 'year')},
        ),
    ]
