# Generated by Django 5.2.7 on 2026-02-08 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_holiday_options_holiday_hijri_day_and_more'),
        ('core', '0007_packagebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='package_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.packagebooking'),
        ),
    ]
