# Generated by Django 5.2.7 on 2026-02-11 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_packagepayment'),
        ('services_app', '0005_alter_popularservice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services_app.service'),
        ),
    ]
