# Generated by Django 5.2.7 on 2026-02-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_appointment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خدمت در زمان رزرو'),
        ),
    ]
