# Generated by Django 5.2.7 on 2026-02-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_appointment_service_name_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, default='staff_photos/person.png', null=True, upload_to='staff_photos/'),
        ),
    ]
