# Generated by Django 5.2.7 on 2025-12-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='popular_services/', verbose_name='تصویر')),
                ('category_slug', models.CharField(max_length=50, verbose_name='اسلاگ دسته\u200cبندی (برای رزرو)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'خدمت پرطرفدار',
                'verbose_name_plural': 'خدمات پرطرفدار',
                'ordering': ['order'],
            },
        ),
    ]
