# Generated by Django 5.2.7 on 2026-01-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_popularservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
