# Generated by Django 5.2.7 on 2026-01-20 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0004_remove_popularservice_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularservice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='popular_services', to='services_app.category'),
            preserve_default=False,
        ),
    ]
