# Generated by Django 5.2.7 on 2026-02-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0005_alter_popularservice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت (تومان)'),
        ),
    ]
