# Generated by Django 5.2.7 on 2026-02-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0006_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='images/beauty_salon.png', null=True, upload_to='services/', verbose_name='عکس اصلی'),
        ),
    ]
