# Generated by Django 5.2.7 on 2026-02-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0007_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularservice',
            name='image',
            field=models.ImageField(default='popular_services/popularservice.jpg', upload_to='popular_services/', verbose_name='تصویر'),
        ),
    ]
