# Generated by Django 5.2.7 on 2026-02-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0008_alter_popularservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularservice',
            name='image',
            field=models.ImageField(upload_to='popular_services/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='عکس اصلی'),
        ),
    ]
