# Generated by Django 5.2.7 on 2026-02-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0009_alter_popularservice_image_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت (تومان)'),
        ),
    ]
