# Generated by Django 5.2.7 on 2026-01-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday_discount_enabled', models.BooleanField(default=True)),
                ('birthday_discount_percent', models.PositiveIntegerField(default=20)),
                ('birthday_discount_valid_days', models.PositiveIntegerField(default=3, help_text='اعتبار کد تخفیف (روز)')),
                ('birthday_notify_days_before', models.PositiveIntegerField(default=7, help_text='چند روز قبل از تولد اعلان ارسال شود (حداقل 3 روز)')),
            ],
        ),
    ]
