# Generated by Django 5.2.7 on 2026-04-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_salonsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
