# Generated by Django 5.2.7 on 2026-01-02 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0003_review_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_rejected',
        ),
    ]
