# Generated by Django 5.2.7 on 2026-01-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0004_remove_review_is_approved_remove_review_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ مدیریت'),
        ),
    ]
