# Generated by Django 5.2.7 on 2026-01-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0005_review_admin_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
