# Generated by Django 5.2.7 on 2026-01-29 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_staff_phone'),
        ('reviews_app', '0006_review_show_on_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking.appointment', verbose_name='نوبت مربوطه'),
            preserve_default=False,
        ),
    ]
