# Generated by Django 5.2.7 on 2026-04-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0007_review_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل رد نظر'),
        ),
    ]
