# Generated by Django 5.2.7 on 2026-04-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0008_review_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rejection_reason',
        ),
    ]
