# Generated by Django 5.2.7 on 2026-02-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_article_show_on_home_article_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='blog/blog.jpg', upload_to='blog/'),
        ),
    ]
